module(load="ommysql")

if ($programname == "tg_https_proxy") then {
    action(
        type="ommysql"
        server="127.0.0.1"
        db="Syslog"
        uid="rsyslog"
        pwd="Password"
        mysqlConfig.file="/etc/rsyslog-mysql.cnf"
        mysqlConfig.section="rsyslog"

        queue.type="LinkedList"
        queue.filename="mysql_queue"
        queue.maxDiskSpace="5g"
        queue.saveOnShutdown="on"

        action.resumeRetryCount="-1"
        action.resumeInterval="5"
        action.errorfile="/var/lib/rsyslog/ommysql-error.log"
    )
}
